version: '3.4'

services:
  vc-db:
    image: mcr.microsoft.com/mssql/server:2019-GA-ubuntu-16.04
    ports:
      - "${DOCKER_SQL_PORT:-1433}:1433"
    expose:  
      - 1433  
    environment: 
      - ACCEPT_EULA=Y
      - MSSQL_PID=Express
      - SA_PASSWORD=v!rto_Labs!

  vcmodulev3.web:
    image: ${DOCKER_REGISTRY-}vcmodulev3web
    build:
      context: .
      dockerfile: src/VCModuleV3.Web/Dockerfile
    environment:
      - ASPNETCORE_Kestrel__Certificates__Default__Password=${DOCKER_PLATFORM_CERT_PASS}
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/${DOCKER_PLATFORM_CERT_NAME}
      - Assets:FileSystem:PublicUrl=https://localhost:${DOCKER_PLATFORM_PORT:-8091}/assets/
      - Content:FileSystem:PublicUrl=https://localhost:${DOCKER_PLATFORM_PORT:-8091}/cms-content/
    ports:
      - "${DOCKER_PLATFORM_PORT:-8091}:443"
    volumes:
      - ./https:/https/
    depends_on:
      - vc-db
