version: '3.4'

services:
  vc-db:
    image: mcr.microsoft.com/mssql/server:2019-GA-ubuntu-16.04
    ports:
      - "${DOCKER_SQL_PORT:-1433}:1433"
    expose:  
      - 1433  
    environment: 
      - ACCEPT_EULA=Y
      - MSSQL_PID=Express
      - SA_PASSWORD=v!rto_Labs!

  vcmodulev3.web:
    image: ${DOCKER_REGISTRY-}vcmodulev3web
    build:
      context: .
      dockerfile: src/VCModuleV3.Web/Dockerfile
    environment:
      - ASPNETCORE_Kestrel__Certificates__Default__Password=virto
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/virto.pfx
    ports:
      - "${DOCKER_PLATFORM_PORT:-8091}:443"
    volumes:
      - ./https:/https/
    depends_on:
      - vc-db
