version: '3.6'

services:
  vcmodulev3.web:
    entrypoint: dotnet VirtoCommerce.Platform.Web.dll
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+
      - ASPNETCORE_HTTPS_PORT=${DOCKER_PLATFORM_PORT:-8091}
      - ConnectionStrings:VirtoCommerce=Data Source=vc-db;Initial Catalog=VirtoCommerce3docker;Persist Security Info=True;User ID=sa;Password=v!rto_Labs!;MultipleActiveResultSets=False;
      - Assets:FileSystem:PublicUrl=https://localhost:${DOCKER_PLATFORM_PORT:-8091}/assets/
      - Content:FileSystem:PublicUrl=https://localhost:${DOCKER_PLATFORM_PORT:-8091}/cms-content/

    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro    